import LANGUAGE from "./LANGUAGE";

const SUPPORTED_LANGUAGE = {
  AUTO: LANGUAGE.AUTO,
  EN_US: LANGUAGE.EN_US,
  ZH_CN: LANGUAGE.ZH_CN,
} as const

type SUPPORTED_LANGUAGE = typeof SUPPORTED_LANGUAGE[keyof typeof SUPPORTED_LANGUAGE]

export default SUPPORTED_LANGUAGE
